version: "3"

services:

  nginx:
    build: nginx/
    ports:
      - "80:80"
      - "443:443"
    environment:
      - BLOG_DOMAIN=${BLOG_DOMAIN}
      - HOOK_DOMAIN=${HOOK_DOMAIN}
      - DNS_PROVIDE=${DNS_PROVIDE}
      - ${DNS_KEY}=${DNS_KEY_VAL}
      - ${DNS_EMAIL}=${DNS_EMAIL_VAL}
    volumes:
      - ./acme.sh/:/root/.acme.sh/
      - ./blog/:/blog/
      - ./hook/:/hook/
      - ./nginx/snippets/:/etc/nginx/snippets/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks: 
      - app-network
    depends_on:
      - php
      - hexo

  php:
    build: php/
    environment:
      - TOKEN=${WEBHOOK_TOKEN}
    volumes:
      - ./hook/:/hook/
      - ./article/:/article/
    networks:
      - app-network
    depends_on:
      - hexo

  hexo:
    build: hexo/
    volumes:
      - ./article/:/Hexo/source/
      - ./themes/:/Hexo/themes/
      - ./blog/:/Hexo/public/
      - ./hexo/conf.d/_config.yml:/Hexo/_config.yml
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
