version: "3"

services:

  nginx:
    build: nginx/
    image: blog_nginx
    container_name: blog_nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - BLOG_DOMAIN=${BLOG_DOMAIN}
      - HOOK_DOMAIN=${HOOK_DOMAIN}
      - DNS_PROVIDE=${DNS_PROVIDE}
      - ${DNS_KEY}=${DNS_KEY_VAL}
      - ${DNS_EMAIL}=${DNS_EMAIL_VAL}
      - DHPARAM=${DHPARAM}
      - ECC_CERT=${ECC_CERT}
    volumes:
      - ./acme.sh/:/root/.acme.sh/
      - ./blog/:/blog/
      - ./hook/:/hook/
      - ./nginx/snippets/:/etc/nginx/snippets/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/dhparam/:/root/dhparam/
    networks:
      - app-network
    depends_on:
      - php
      - hexo

  php:
    build: php/
    image: blog_php
    container_name: blog_hook
    environment:
      - TOKEN=${WEBHOOK_TOKEN}
    volumes:
      - ./hook/:/hook/
      - ./article/:/article/
    networks:
      - app-network
    depends_on:
      - hexo

  hexo:
    build: hexo/
    image: blog_hexo
    container_name: blog_hexo
    environment:
      - ARTICLE_REP=${ARTICLE_REP}
      - THEME_REP=${THEME_REP}
      - THEME_PKG=${THEME_PKG}
      - THEME_NAME=${THEME_NAME}
    volumes:
      - ./article/:/Hexo/source/
      - ./themes/:/Hexo/themes/
      - ./blog/:/Hexo/public/
      - ./hexo/conf.d/_config.yml:/Hexo/_config.yml
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
